GET http://127.0.0.1:5000/users

###
GET http://127.0.0.1:5000/users/64ffea1e2b646cdc9f5afbe5

###
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
    "name": "Dea",
    "email": "deaimoet@gmail.com",
    "gender": "Female"
}

###
PATCH http://127.0.0.1:5000/users/64ffea1e2b646cdc9f5afbe5
Content-Type: application/json

{
    "name": "golang",
    "email": "golang@gmail.com",
    "gender": "Male"
}

###
DELETE http://127.0.0.1:5000/users/64ffea1e2b646cdc9f5afbe5